name: Run Newsletter Automation

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run article analysis
        run: python full_article_analyzer.py

      - name: Run newsletter generator
        run: python enhanced_newsletter.py

      - name: Move newsletter files to GitHub Pages
        run: |
          mkdir -p docs
          mv critical_newsletter_*.txt docs/
          mv full_articles_*.json docs/
          git add docs/
          git commit -m "Move newsletter files to GitHub Pages" || exit 0
          git push origin main

      - name: Verify GitHub Pages Deployment
        run: echo "Files should now be available in GitHub Pages under /docs/"

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update newsletter - $(date)" || exit 0
          git push origin main
